# Generated by Django 2.2.1 on 2022-06-14 06:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('google_id', models.IntegerField(default=-1)),
                ('task_name', models.TextField(max_length=255)),
                ('is_completed', models.BooleanField(default=False)),
                ('task_start_date', models.DateTimeField(verbose_name=datetime.datetime(2022, 6, 14, 12, 2, 16, 934564))),
                ('task_end_date', models.DateTimeField()),
                ('task_importance', models.IntegerField(default=0, max_length=2)),
            ],
        ),
    ]
