# Generated by Django 2.2.1 on 2022-06-17 05:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interact', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task_importance',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_start_date',
            field=models.DateTimeField(verbose_name=datetime.datetime(2022, 6, 17, 10, 57, 35, 878802)),
        ),
    ]
